<a href="https://colab.research.google.com/github/R-Madhuram/UC-BerkeleyCapstone_CreditCardFraudDetection/blob/main/notebooks/AutoML_ensembleModels/13_Auto_ML_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Auto ML Model Using Pycaret

In [ ]:
!pip install --pre pycaret

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.1/480.1 KB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 KB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 KB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 28.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 KB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 66.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 11.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.0/150.0 KB 18.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   

In [ ]:
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV

In [ ]:
import xgboost

In [ ]:
import pandas as pd
import numpy as np
import pickle

## Importing helper functions



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Import the helper function files
# Importing the helper_functions file
!cp /content/drive/MyDrive/PCMALAI_UCBerkeley_Capstone/Notebooks/helper_functions.py helper_functions.py
!cp /content/drive/MyDrive/PCMALAI_UCBerkeley_Capstone/Notebooks/helper_functions_ml.py helper_functions_ml.py

In [ ]:
# Import the helper functions
# Import the required functions from the helper function file
from helper_functions_ml import createMetricsDF,computeModelMetrics,computeAndPlotMetrics

## Import the Data (training and testing)

In [ ]:
# Import training data
!cp '/content/drive/MyDrive/PCMALAI_UCBerkeley_Capstone/Classification_products/df.csv' 'df.csv'

In [ ]:
# Read the training data
df_train = pd.read_csv('df.csv')
print(df_train.head())

df_train = df_train.drop('Unnamed: 0', axis=1)
df_train.head(3)
print(df_train.shape)

   Unnamed: 0  TransactionID  isFraud  TransactionDT  TransactionAmt  \
0           0        2987000        0          86400        1.835691   
1           1        2987001        0          86401        1.462398   
2           2        2987002        0          86469        1.770852   
3           3        2987003        0          86499        1.698970   
4           4        2987004        0          86506        1.698970   

   ProductCD  card1  card2  card3  card4  ...  id_36  id_37  id_38  \
0          4  13926   -1.0  150.0      1  ...      2      2      2   
1          4   2755  404.0  150.0      2  ...      2      2      2   
2          4   4663  490.0  150.0      4  ...      2      2      2   
3          4  18132  567.0  150.0      2  ...      2      2      2   
4          1   4497  514.0  150.0      2  ...      0      1      1   

   DeviceType  DeviceInfo  P_emaildomain_addr1_card1  card1_card2  \
0           1        1735                      63363         3655   
1       

In [ ]:
# CP cannot be used to copy file here because numFolds is a variable and hence the filenames will change based on the number of folds.
# instead of using linux CP command we use SHUTIL copy 

# read the K fold train and dev indices

numFolds = 3

import shutil # file copy package. 

srcFileName = '/content/drive/MyDrive/PCMALAI_UCBerkeley_Capstone/Classification_products/train_dev_indices_' + str(numFolds) + '.pickle' 
train_dev_indices_file = 'train_dev_indices_' + str(numFolds) + '.pickle'
# !cp  srcFileName destFileName
shutil.copyfile(srcFileName, train_dev_indices_file)


'train_dev_indices_3.pickle'

In [ ]:
# read the train dev indices file
# train_dev_indices_df = pd.read_csv(train_dev_indices_file)
# train_dev_indices_df.head()

with open(train_dev_indices_file, 'rb') as handle:
    train_dev_indices = pickle.load(handle)
train_dev_indices

{'train': [array([195756, 195757, 195758, ..., 590537, 590538, 590539]),
  array([     0,      1,      2, ..., 590537, 590538, 590539]),
  array([     0,      1,      2, ..., 397410, 397417, 397418])],
 'dev': [array([     0,      1,      2, ..., 221151, 221172, 221182]),
  array([195756, 195757, 195758, ..., 397410, 397417, 397418]),
  array([393481, 393482, 393483, ..., 590537, 590538, 590539])]}

In [ ]:
# Getting dataready
X = df_train.drop(columns = ['isFraud','TransactionID'])
y = df_train['isFraud']

In [ ]:
# List of categorical and numerical columns in merged dataset

## Numerical columns

num_column_lst_final = []
for icol in X.columns:
  if X[icol].dtypes in ['float64', 'int64']:
    num_column_lst_final.append(icol)
print(f"The columns that have numerical features are: '{num_column_lst_final}'")
print(f"The number of columns that have numerical features are: '{len(num_column_lst_final)}'")

print('\n')

## Categorical Columns
cat_column_lst_final = []
for icol in X.columns:
  if X[icol].dtypes in ['object']:
    cat_column_lst_final.append(icol)
print(f"The columns that have categorical features are: '{cat_column_lst_final}'")
print(f"The number of columns that have categorical features are: '{len(cat_column_lst_final)}'")


The columns that have numerical features are: '['TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C3', 'C5', 'D1', 'D3', 'D4', 'D8', 'D9', 'D10', 'D13', 'D14', 'M1', 'M2', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'V1', 'V2', 'V4', 'V6', 'V10', 'V12', 'V14', 'V15', 'V19', 'V23', 'V25', 'V27', 'V35', 'V37', 'V39', 'V44', 'V46', 'V53', 'V55', 'V61', 'V66', 'V75', 'V77', 'V82', 'V86', 'V95', 'V98', 'V99', 'V104', 'V107', 'V108', 'V109', 'V117', 'V118', 'V120', 'V121', 'V123', 'V124', 'V129', 'V135', 'V138', 'V139', 'V141', 'V144', 'V148', 'V161', 'V169', 'V170', 'V172', 'V173', 'V174', 'V184', 'V194', 'V208', 'V209', 'V214', 'V220', 'V221', 'V223', 'V224', 'V226', 'V227', 'V228', 'V238', 'V240', 'V241', 'V250', 'V260', 'V270', 'V281', 'V282', 'V284', 'V286', 'V288', 'V290', 'V300', 'V305', 'V313', 'id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06', 'id_07', 'id_08',

## Models

In [ ]:
from pycaret.classification import setup,create_model,tune_model

In [ ]:
exp = setup(data= df_train, target='isFraud',session_id=42,use_gpu=True)

### XGBoost Model

In [ ]:
# xgboost model
xgb = create_model('xgboost')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 14.6 MB/s eta 0:00:00


### LightGBM Model

In [ ]:
exp = setup(data= df_train, target='isFraud',session_id=42,use_gpu=True)
lightgbm = create_model('lightgbm')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [ ]:
!pip install pycaret[full]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 KB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.2/92.2 KB 9.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 61.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.4/572.4 KB 35.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 KB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 KB 6.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 MB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.4/364.4 KB 29.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 61.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 KB

### CatBoost Model

In [ ]:
from pycaret.classification import setup,create_model,tune_model,stack_models

In [ ]:
exp = setup(data= df_train, target='isFraud',session_id=42,use_gpu=True)
catboost = create_model('catboost')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

### Stacked Classifier 1 (DT Meta model)

In [ ]:
dt = create_model('dt')
stacker_dt = stack_models(estimator_list = [lightgbm,xgb,catboost],meta_model=dt)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

### Stacked Classifier 2 (AdaBoost Meta model)

In [ ]:
ada = create_model('ada')
stacker_ada = stack_models(estimator_list = [lightgbm,xgb,catboost],meta_model=ada)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Initiated  . . . . . . . . . . . . . . . . . .             05:00:36
Status     . . . . . . . . . . . . . . . . . .     Finalizing Model
Estimator  . . . . . . . . . . . . . . . . . .  Stacking Classifier

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

### Stacked Classifier 3 (LightGBM Meta model)

In [ ]:
stacker_lightgbm = stack_models(estimator_list = [lightgbm,xgb,catboost],meta_model=lightgbm)

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

### Stacked Classifier 4 (Random Forest Meta model)

In [ ]:
rf = create_model('rf')
stacker_rf = stack_models(estimator_list = [lightgbm,xgb,catboost],meta_model=rf)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Initiated  . . . . . . . . . . . . . . . . . .             11:02:49
Status     . . . . . . . . . . . . . . . . . .     Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Stacking Classifier

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

## Result Summary

Auto-ML using PyCaret library provided by python is an attarctive option for complex machine learning tasks, since hyper-Parameter tuning is time consuming and computationally expensive for ensemble models and stacked meta models. 

We built the three best boosting models from our previous iterations namely, XGBoost, LightGBM, and CatBoost models and stacked them using various meta/base estimators (Decision tree, Ada Boost, LightGBM and Random Forest). 

The stacking classfiers with adaboost/ Light GBM meta-estimators presented thamselves with a ROC-AUC score of 0.94 and a recall score of 0.54. Hence we chose to deploy either adaboost or Light GBM to Azure cloud storage. 

These two models are also the best models that we have obtained in this project yeilding the highes ROC-AUC score. 

## Model Storage in Azure

In [ ]:
from pycaret.classification import finalize_model
final_ada = finalize_model(stacker_ada)
print(final_ada)

Pipeline(memory=FastMemory(location=/tmp/joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['TransactionID', 'TransactionDT',
                                             'TransactionAmt', 'ProductCD',
                                             'card1', 'card2', 'card3', 'card4',
                                             'card5', 'card6', 'addr1', 'addr2',
                                             'dist1', 'dist2', 'P_emaildomain',
                                             'R_emaildomain', 'C1', 'C3', 'C5',
                                             'D1', 'D3', 'D4', 'D8', 'D9',
                                             'D10', 'D13', 'D14', '...
                                                               objective='binary:logistic',
                                                               predictor=None, ...)),
                                                ('CatBoost Cl

In [ ]:
from pycaret.classification import save_model,deploy_model, load_model
model_dir = '/content/drive/MyDrive/PCMALAI_UCBerkeley_Capstone/Classification_products/'
model_name = 'Final_StackedAda_model'

In [ ]:
save_model(final_ada, model_dir + model_name)

In [ ]:
final_ada = load_model(model_dir + model_name)

Transformation Pipeline and Model Successfully Loaded


In [ ]:
azure_connection_string = 'DefaultEndpointsProtocol=https;AccountName=madhuramdeployment;AccountKey=l1nkTN9+kIK4gj2OzvNR+kHhIK7sr4AtBe3g5mWjXn2Bn1sf3Rke6wwWyb0RDRcWoYs83hjkPr9z+AStLRuoHw==;EndpointSuffix=core.windows.net'

In [ ]:
import os
os.environ['AZURE_STORAGE_CONNECTION_STRING'] = azure_connection_string

In [ ]:
!pip install azure-storage-blob

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
deploy_model(model = final_ada, model_name = model_name, platform = 'azure', authentication = {'container' : 'madhuramdeployment'})

Model Successfully Deployed on Azure Storage Blob


## Model Deployment in Local Host

In [ ]:
from pycaret.classification import create_api
create_api(final_ada, 'ada_api')

API successfully created. This function only creates a POST API, it doesn't run it automatically. To run your API, please run this command --> !python ada_api.py


In [ ]:
# create docker
from pycaret.classification import create_docker
create_docker('ada_api')

In [ ]:
from pycaret.classification import create_app
create_app(final_ada)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Note: opening Chrome Inspector may crash demo inside Colab notebooks.

To create a public link, set `share=True` in `launch()`.


<IPython.core.display.Javascript object>

## Future Work

We can further improve the prformance of these models through augumenting them with an unsupervised learning technique like Isolation forest for detecting anamalous observations. 

Also Deep Learning methods for tabular data can be utilized in combination with machine learning methods built above or alone to improve the overall perfomance of the model to acheive the business objective of identifying the fraud transactions. 